---
- hosts: ws
  become: true
  tasks:
    - name: update all packages
      package:
        name: '*'
        state: latest
    - name:
      yum:
        name: httpd
        state: latest
    - name: Start Daemon
      service:
        name: httpd
        state: started
        enabled: true
    #- name: Delete file if exists
      #file:
       #path: /var/www/html/index.html
       #state: absent
      #ignore_errors: true

    - name: create a file
      file:
       dest: /var/www/html/index.html
       state: touch

    - name: Add content to our file
      lineinfile:
       path: /var/www/html/index.html
       line: <h1> This is our ansible webserver and we are making good progress </h1>
      notify: Restart Daemon

  handlers: 
   - name: Restart Daemon
     service:
        name: httpd
        state: restarted
     