---
- hosts: ws
  become: true
  ignore_errors: 1
  gather_facts: true
  vars_files:
      - vars.yml
  tasks:
- name: Download file using Ansible
  hosts: localhost
  tasks:
- name: Download package
  get_url:
  url: "{{ LINK_URL }}"
  dest: "{{ DESTINATION }}"

- name: Delete file
  ansible.builtin.file:
  path: "{{ DESTINATION }}"
  state: absent
